#!/bin/sh
### BEGIN INIT INFO
# Provides:          readhub-web
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: readhub-web initscript
# Description:       readhub-web
### END INIT INFO
 
# Original author: Forrest Robertson
 
# Do NOT "set -e"
 
DAEMON='/usr/local/rbenv/shims/bundle exec /usr/local/rbenv/shims/thin'
SCRIPT_NAME=/etc/init.d/readhub-web
CONFIG_FILE=/etc/thin/readhub-web.yml
APP_PATH=/vagrant
 
# libgit2 sees running process's HOME
export HOME=/var/www
 
# Exit if the package is not installed
#[ -x "$DAEMON" ] || exit 0
 
cd $APP_PATH

case "$1" in
  start)
   # $DAEMON start --all $CONFIG_PATH
  $DAEMON start --config $CONFIG_FILE
  ;;
  stop)
  # $DAEMON stop --all $CONFIG_PATH
  $DAEMON stop --config $CONFIG_FILE
  ;;
  restart)
  # $DAEMON restart --all $CONFIG_PATH
  $DAEMON restart --config $CONFIG_FILE
  ;;
  *)
  echo "Usage: $SCRIPT_NAME {start|stop|restart}" >&2
  exit 3
  ;;
esac
