#!/bin/bash

exec > >(tee -a $GL_ADMIN_BASE/logs/post-receive.log) 2>&1
set -e

if [ "$GL_USER" = "admin" ] ; then
    exit 0
fi

rev=$(grep refs/heads/master | cut -d' ' -f2)
if [ -z "$rev" ] ; then
    exit 0
fi

curl -fsSL "http://localhost:4000/repos/$GL_REPO/$rev/new" > /dev/null

/usr/local/bin/checkout-and-index-wrapper "$GL_REPO_BASE" "$GL_REPO" $rev

exit 0
